In [2]:
import pyodbc
import pandas as pd

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=DESKTOP-OKVRG6P\\SQLEXPRESS;"
    "DATABASE=MotoDB;"
    "Trusted_Connection=yes;"
)

df = pd.read_sql("SELECT * FROM dbo.VehicleSales", conn)
df.head()

C:\Users\Abd el Aziz\AppData\Local\Temp\ipykernel_24816\786785408.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM dbo.VehicleSales", conn)

,Id,Year,Make,Model,Trim,Body,Transmission,VIN,State,ConditionValue,Odometer,Color,Interior,Seller,MMR,SellingPrice,SaleDate
0,2,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,2014-12-16 04:30:00
1,3,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,2014-12-16 04:30:00
2,4,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,2015-01-14 20:30:00
3,5,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,2015-01-28 20:30:00
4,6,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,2014-12-18 04:30:00

In [3]:
df.shape

(558837, 17)

In [4]:
df.isna().sum()

Id                    0
Year                  0
Make              10301
Model             10399
Trim              10651
Body              13195
Transmission      65352
VIN                   4
State                 0
ConditionValue    11820
Odometer             94
Color               749
Interior            749
Seller                0
MMR                  38
SellingPrice         12
SaleDate             38
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 17 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Id              558837 non-null  int64
 1   Year            558837 non-null  int64
 2   Make            548536 non-null  object
 3   Model           548438 non-null  object
 4   Trim            548186 non-null  object
 5   Body            545642 non-null  object
 6   Transmission    493485 non-null  object
 7   VIN             558833 non-null  object
 8   State           558837 non-null  object
 9   ConditionValue  547017 non-null  float64
 10  Odometer        558743 non-null  float64
 11  Color           558088 non-null  object
 12  Interior        558088 non-null  object
 13  Seller          558837 non-null  object
 14  MMR             558799 non-null  float64
 15  SellingPrice    558825 non-null  float64
 16  SaleDate        558799 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(2), object(10)
memory usage: 72.5+ MB

In [8]:
df.describe()

,Id,Year,ConditionValue,Odometer,MMR,SellingPrice,SaleDate
count,558837.000000,558837.000000,547017.000000,558743.000000,558799.000000,558825.000000,558799
mean,279420.000000,2010.038927,30.672365,68320.017767,13769.377495,13611.358810,2015-03-06 00:09:10.521385472
min,2.000000,1982.000000,1.000000,1.000000,25.000000,1.000000,2014-01-01 01:15:00
25%,139711.000000,2007.000000,23.000000,28371.000000,7100.000000,6900.000000,2015-01-20 18:00:00
50%,279420.000000,2012.000000,35.000000,52254.000000,12250.000000,12100.000000,2015-02-12 19:20:00
75%,419129.000000,2013.000000,42.000000,99109.000000,18300.000000,18200.000000,2015-05-21 19:00:00
max,558838.000000,2015.000000,49.000000,999999.000000,182000.000000,230000.000000,2015-07-20 19:30:00
std,161322.490529,3.966864,13.402832,53398.542821,9679.967174,9749.501628,NaN

In [9]:
df.to_csv("data.csv", index=False)